# Assigning
p= 90
p= "sweety"
b= "pappy"
c= p+b

p= p+"pappy"
print(p)

# Assiging same value to multiple
a=b=c=10
print(b)
print(c)
print(a)
a,b,c= 5,4,3
print(a,b,c)
print(a+b+c)

# casting 
a= 53
b= float(a)
print(a)
a= float(a)
print(a,b)
# a= a+"sweety"
# print(a)

c= str(a)
print(c)
print(type(c))
c= c+"sweety"
print(c)
# d= int(c)
# print(d)
# d= 57.0
# d= d+"pappy"
# print(d)

#0 --> False
#!=0 ---> True
f= 2
f= bool(f)
print(f)
# "" -> False
# ! "" -> True
op=""
p= bool(op)
print(p)
  
# Input
name = input("Enter Your Name:")
print(name)

y= int(input("Enter your Id :"))
z= float(input("Enter your score :"))
         

